/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#002718",
        "primary-container": "#133e2b",
        "on-primary": "#ffffff",
        "on-primary-container": "#7da990",
        "primary-fixed": "#bfedd2",
        "primary-fixed-dim": "#a3d1b6",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#254f3a",

        "secondary": "#026d41",
        "secondary-container": "#9af2bb",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#0d7145",
        "secondary-fixed": "#9cf5be",
        "secondary-fixed-dim": "#81d9a3",
        "on-secondary-fixed": "#002110",
        "on-secondary-fixed-variant": "#005230",

        "tertiary": "#371a00",
        "tertiary-container": "#572c00",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ec861d",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",

        "surface": "#f8f9ff",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#ccdbf4",
        "surface-variant": "#d5e3fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dde9ff",
        "surface-container-highest": "#d5e3fd",
        "on-surface": "#0d1c2f",
        "on-surface-variant": "#414943",
        "inverse-surface": "#233144",
        "inverse-on-surface": "#ebf1ff",
        "surface-tint": "#3d6751",

        "background": "#f8f9ff",
        "on-background": "#0d1c2f",

        "outline": "#717973",
        "outline-variant": "#c1c8c1",

        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "sm": "0.25rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "2xl": "2rem",
        "full": "9999px"
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-xl-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "30px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-xl": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "18px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" }],
        "metric-number": ["32px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      boxShadow: {
        "xs": "0 1px 2px rgba(19, 62, 43, 0.05)",
        "elevation-1": "0 1px 3px rgba(19, 62, 43, 0.05)",
        "elevation-2": "0 4px 12px -2px rgba(19, 62, 43, 0.08), 0 2px 6px -1px rgba(19, 62, 43, 0.04)",
        "elevation-3": "0 16px 32px -4px rgba(14, 41, 28, 0.16), 0 4px 12px rgba(14, 41, 28, 0.08)",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-sm": "1rem",
        "margin": "2rem",
        "margin-sm": "1rem",
        "margin-lg": "3rem"
      },
      fontFamily: {
        "sans": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Plus Jakarta Sans", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "metric": ["Inter", "monospace"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "metric-number": ["Inter", "monospace"]
      }
    },
  },
  plugins: [],
}
